/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatclient;

import java.awt.Color;
import javax.swing.DefaultListModel;

/**
 *
 * @author Nicola
 */
public class Client extends javax.swing.JFrame {

    private Cl cl;
    private DefaultListModel lista;
    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
        
        cl = new Cl(this);
        lista = new DefaultListModel();
        
        btnConnect.setBackground(Color.green);
        btnDisconnetti.setBackground(Color.red);
    }
    
    
    
    //Ritorna il pannello per ritornare messaggi o aggiungerne
    public void setMessaggi(String testo)
    {
        txtMessaggi.setText(testo);
    }
    
    //Ritorna il pannello per ritornare messaggi o aggiungerne
    public String getMessaggi()
    {
        return txtMessaggi.getText();
    }
    
    //Ritorna il pannello per ritornare messaggi o aggiungerne
    public void setMessaggio()
    {
        txtMessaggio.setText("");
    }
    
      
    //Ritorna la stringa per aggiungere/rimuovere
    public void setUser(String testo)
    {
        txtUsername.setText(testo);
    }
    
    //RItorna stringa utenti
    public String getUsername()
    {
        return this.txtUsername.getText();    
    }
    
    //RItorna stringa utenti
    public String getPassword()
    {
        return this.txtPassword.getText();    
    }
    
    public void setPassword()
    {
        txtUsername.setText("");
    }
    
    //Ritorna status show ip
    public boolean getShowStatus()
    {
        return showIp.isSelected();
    }
    
    public void setUtenti(String[] array)
    {
        lista.removeAllElements();
        
        for(int y = 1; y < array.length; y++)
        {
            lista.addElement(array[y]);
        }
        
        listUsers.setModel(lista);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtUsername = new javax.swing.JTextPane();
        btnConnect = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMessaggi = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMessaggio = new javax.swing.JTextPane();
        btnInvia = new javax.swing.JButton();
        btnDisconnetti = new javax.swing.JButton();
        showIp = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtPassword = new javax.swing.JTextPane();
        btnPrivateMessage = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        listUsers = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username");

        txtUsername.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtUsernameCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(txtUsername);

        btnConnect.setText("Connect");
        btnConnect.setEnabled(false);
        btnConnect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConnectMouseClicked(evt);
            }
        });

        txtMessaggi.setColumns(20);
        txtMessaggi.setRows(5);
        txtMessaggi.setFocusable(false);
        jScrollPane2.setViewportView(txtMessaggi);

        jScrollPane3.setViewportView(txtMessaggio);

        btnInvia.setText("Invia");
        btnInvia.setEnabled(false);
        btnInvia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInviaMouseClicked(evt);
            }
        });

        btnDisconnetti.setText("Disconnect");
        btnDisconnetti.setEnabled(false);
        btnDisconnetti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDisconnettiMouseClicked(evt);
            }
        });

        showIp.setText("Show IP");
        showIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showIpActionPerformed(evt);
            }
        });

        jLabel2.setText("Password: ");

        jScrollPane4.setViewportView(txtPassword);

        btnPrivateMessage.setText("Private Message");
        btnPrivateMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrivateMessageMouseClicked(evt);
            }
        });

        jScrollPane5.setViewportView(listUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showIp)
                        .addGap(18, 18, 18)
                        .addComponent(btnConnect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDisconnetti))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInvia))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane5)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrivateMessage)
                        .addGap(156, 156, 156)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConnect)
                            .addComponent(btnDisconnetti))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(showIp)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInvia)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnPrivateMessage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnectMouseClicked
        // TODO add your handling code here:
        cl.connect();
    }//GEN-LAST:event_btnConnectMouseClicked

    private void btnInviaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInviaMouseClicked
        // TODO add your handling code here:
        cl.invia(txtMessaggio.getText());
    }//GEN-LAST:event_btnInviaMouseClicked

    private void btnDisconnettiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDisconnettiMouseClicked
        // TODO add your handling code here:
        cl.disconnetti();
        
    }//GEN-LAST:event_btnDisconnettiMouseClicked

    private void txtUsernameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtUsernameCaretUpdate
        // TODO add your handling code here:
        btnConnect.setEnabled(true);
        btnDisconnetti.setEnabled(true);
        btnInvia.setEnabled(true);
    }//GEN-LAST:event_txtUsernameCaretUpdate

    private void showIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showIpActionPerformed

    private void btnPrivateMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrivateMessageMouseClicked
        // TODO add your handling code here:
        String utente = listUsers.getSelectedValue().toString();
        cl.inviaPrivate(utente, txtMessaggio.getText());
    }//GEN-LAST:event_btnPrivateMessageMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnDisconnetti;
    private javax.swing.JButton btnInvia;
    private javax.swing.JButton btnPrivateMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> listUsers;
    private javax.swing.JCheckBox showIp;
    private javax.swing.JTextArea txtMessaggi;
    private javax.swing.JTextPane txtMessaggio;
    private javax.swing.JTextPane txtPassword;
    private javax.swing.JTextPane txtUsername;
    // End of variables declaration//GEN-END:variables
}
